# 베이스 이미지 설정
FROM eclipse-temurin:17

# JAR 파일 이름을 빌드 시 설정 가능하게 처리
ARG JAR_FILE=build/libs/*.jar

# Build-time ARG 정의
ARG DATABASE_USERNAME
ARG DATABASE_PASSWORD
ARG DATABASE_URL
ARG AWS_REGION
ARG JWT_SECRET

# ARG를 런타임 ENV로 변환
ENV DATABASE_USERNAME=$DATABASE_USERNAME
ENV DATABASE_PASSWORD=$DATABASE_PASSWORD
ENV DATABASE_URL=$DATABASE_URL
ENV AWS_REGION=$AWS_REGION
ENV JWT_SECRET=$JWT_SECRET

# JAR 파일을 컨테이너 내부로 복사
COPY ${JAR_FILE} app.jar

# 컨테이너 실행 명령어 설정
CMD ["java","-jar","/app.jar"]
