spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://223.130.152.102/bridge_db
    username: user
    password: 1234

  data:
    mongodb:
      uri: mongodb://user:1234@223.130.152.102:27017/brand_space_db

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 319

file:
  upload-dir: /Users/admin/git/be-repository/Unicorn/uploads

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.springframework: DEBUG
    com.ohgiraffers: DEBUG
