spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: '${{ DATABASE_URL }}'
    username: '${{ DATABASE_USERNAME }}'
    password: '${{ DATABASE_PASSWORD }}'

  data:
    mongodb:
      uri: mongodb://user:1234@223.130.152.102:27017/brand_space_db

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 319

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.springframework: DEBUG
    com.ohgiraffers: DEBUG

cloud:
  aws:
    s3:
      bucket: bucat
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}

jwt:
  secret: ${JWT_SECRET}
